import Head from 'next/head'

import styles from '../styles/Home.module.css'

import { useEffect, useState } from 'react'

import { signInWithGooglePopUp, loginWithEmailandPassword, createUserDocument } from '../auth/firebase/firebase'

export default function Home() {

  const [auth, setAuth] = useState(false)

  const [state, setState] = useState({

    name: '',
    email: '',
    password: '',

  })

 

  const {name, email, password} = state

  const logInHandler = async (e) =>{

    e.preventDefault();
    
    const {user} = await signInWithGooglePopUp()

    console.log("from login function: ",user);

    const userRef = await createUserDocument(user)
    console.log(userRef);

    setAuth(true)

  }


  const emailSubmitHandler = (e) =>{

    e.preventDefault();
    loginWithEmailandPassword(email, password)
    console.log("Email submit");
    
  }


  const inputChangeHandler = (name) => (e) =>{

    setState({...state, [name]: e.target.value})
    console.log(e.target.value);

  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Up Green 🍃</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>


        {auth && <button>Log Out</button>}


        {!auth && (

          <>

        <button onClick={logInHandler}>Log In with Google</button>

        <form onSubmit={emailSubmitHandler}>

          <input type="email" placeholder="Email"  value={email} onChange={inputChangeHandler("email")}/>

          <input type="password" placeholder="Password" value={password} onChange={inputChangeHandler("password")}/>

          <button type="submit">Log In</button>

        </form>
        </>
        )
  }

      </main>
    </div>
  )
}
